### ISSUE TITLE
Upload app archive to GitHub

### ISSUE THREAD

**Issue by ChristophWurst** [ChristophWurst/krankerl#8]
Should be doable https://developer.github.com/v3/repos/releases/

**Comment by juliushaertl** [comment]
It would be great, if it would also push a new tag and add a changelog from CHANGELOG.md (as it is already used by the NC app store) to the release description.

**Comment by rullzer** [comment]
Ok so I was going over the API

In short. If you create the release from the API. You get a url back to upload the assets to.
This should be a simple POST\

In short. What I would vote for is to say we create a krankler release command that will do

`krankerl release <TAG>`

1. This will build the asset (already there)
2. Create a release from the tag supplied (TODO)
3. Upload the assets to the URL provided in 2 (TODO)
4. Publish to the appstore (already there)

Of course it is probably easiest to just do step 2 and 3 as separate commands first. So we can test them properly.
I hope to have some time for that soon also to dig more into my rust skillz

**Comment by korelstar** [comment]
Just for your information: In the meanwhile, I've created a release tool with GitHub actions: https://github.com/korelstar/nextcloud-app-release-tool

This tool builds the app, signs it, creates a release on GitHub and publishes it to the Nextcloud appstore. I'm using it since some months for the notes app. Please feel free to use it for other apps. I just added a documentation to the README.

**Comment by ChristophWurst** [comment]
An integration of this tool into a github action seems like the better option these days indeed.
